### ISSUE TITLE
The measurements can go to zero occasionaly

### ISSUE THREAD

**Issue by S-Dafarra** [robotology-playground/xsensmt-yarp-driver#5]
During some experiments it happened that the raw measurement coming from the IMU dropped to zero for about 20ms.
![dropimu](https://user-images.githubusercontent.com/18591940/36393727-0904740a-15b1-11e8-928f-bc593f46a384.png)
cc @traversaro @DanielePucci

**Comment by traversaro** [comment]
I suspect that we are missing some checks in https://github.com/robotology-playground/xsensmt-yarp-driver/blob/master/xsensmt/XsensMT.cpp#L221 , but it is difficult to know without further information. It would be helpful to know if only the orientation measurement is going to zero or also the other measurements.

**Comment by S-Dafarra** [comment]
Thanks @traversaro! Actually only the orientation goes to zero! I did not notice it in a first instance.
![screenshot from 2018-02-20 13-07-27](https://user-images.githubusercontent.com/18591940/36423211-42bef600-163f-11e8-8b74-4d2d4d9557a6.png)

**Comment by traversaro** [comment]
Then I think that for the other measurements the validity checks are enforced by `if [...].size == 3`, but there is no such check for euler orientation: https://github.com/robotology-playground/xsensmt-yarp-driver/blob/master/xsensmt/XsensMT.cpp#L229 .

**Comment by traversaro** [comment]
Can you check if the fix in https://github.com/robotology-playground/xsensmt-yarp-driver/issues/5 is working? Thanks
